version: '3.8'

services:
  postgres:
    container_name: hana-pg
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hana
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
